spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: safin
    password: safin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  domain:
    user-settings:
      currency: "RUB"
      percentFee: 5
      timezone: "Asia/Yekaternburg"
      language: "ru"
    payouts-settings:
      balance: 0
    donation-settings:
      is-message-moderate: false
      is-remove-links: false
      max-count-of-symbols: 200
      min-sum: 20
      max-sum: 1000

