spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: safin
    password: safin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-secret: 6a3e6d533b28d48fbe3c7569305e8abc1a7695d0
            client-id: ca701e5272360acb5906
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.security: DEBUG
application:
  domain:
    user-settings:
      currency: "RUB"
      percentFee: 5
      timezone: "Asia/Yekaternburg"
      language: "ru"
    payouts-settings:
      balance: 0
    donation-settings:
      is-message-moderate: false
      is-remove-links: false
      max-count-of-symbols: 200
      min-sum: 20
      max-sum: 1000
    available-currencies:
      - 'RUB'
      - 'USD'
      - 'CNY'
      - 'JPY'
    maxCountOfPayoutsMethods: 3
    cardFee: 5

